# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(440, 375)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # ADD ITEM
        self.additem_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.addItem())
        self.additem_pushButton.setGeometry(QtCore.QRect(5, 50, 121, 41))
        self.additem_pushButton.setObjectName("additem_pushButton")
        # INPUT FIELD
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 411, 31))
        self.lineEdit.setObjectName("lineEdit")
        # LIST
        self.mylist_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.mylist_listWidget.setGeometry(QtCore.QRect(10, 100, 411, 211))
        self.mylist_listWidget.setObjectName("mylist_listWidget")
        # DELETE ITEM
        self.deleteitem_pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.deleteItem())
        self.deleteitem_pushButton_2.setGeometry(QtCore.QRect(150, 50, 131, 41))
        self.deleteitem_pushButton_2.setObjectName("deleteitem_pushButton_2")
        # CLEAR ALL
        self.clearall_pushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clearAll())
        self.clearall_pushButton_3.setGeometry(QtCore.QRect(300, 50, 121, 41))
        self.clearall_pushButton_3.setObjectName("clearall_pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def addItem(self):
        item = self.lineEdit.text()
        self.mylist_listWidget.addItem(item)
        self.lineEdit.setText("")

    def deleteItem(self):
        # Grab the selected row
        clickedId = self.mylist_listWidget.currentRow()
        # Delete selected row
        self.mylist_listWidget.takeItem(clickedId)

    def clearAll(self):
        self.mylist_listWidget.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To do list"))
        self.additem_pushButton.setText(_translate("MainWindow", "Add Items"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Type your items"))
        self.deleteitem_pushButton_2.setText(_translate("MainWindow", "Delete Items"))
        self.clearall_pushButton_3.setText(_translate("MainWindow", "Clear All"))
